web/router.ex
defmodule SpreedlyAirlinesElixir.Router do
  use SpreedlyAirlinesElixir.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SpreedlyAirlinesElixir do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/transactions", TransactionController, :index
    get "/transactions/:token", TransactionController, :show

    scope "/flights" do 
      get "/", FlightController, :index
      get "/:id", FlightController, :show
      post "/purchase", FlightController, :purchase
      get "/purchase/confirmation", FlightController, :confirmation
    end 
end

  # Other scopes may use custom stacks.
  # scope "/api", SpreedlyAirlinesElixir do
  #   pipe_through :api
  # end
end

lib/spreedly_airlines_elixir/endpoint.ex
defmodule SpreedlyAirlinesElixir.Endpoint do
  use Phoenix.Endpoint, otp_app: :spreedly_airlines_elixir

  socket "/socket", SpreedlyAirlinesElixir.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :spreedly_airlines_elixir, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_spreedly_airlines_elixir_key",
    signing_salt: "C6vnwqoU"

  plug SpreedlyAirlinesElixir.Router
end

web/controllers/flight_controller.ex
defmodule SpreedlyAirlinesElixir.FlightController do
  use SpreedlyAirlinesElixir.Web, :controller

  require Logger
  require Spreedly

  @spreedly Application.get_env(:spreedly_airlines_elixir, :spreedly)

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def purchase(conn, %{"flight_form" => params}) do
    flight_id = params["id"]
    flight = find_flight(flight_id)

    response = make_purchase(flight, params)
    delivery_response = deliver_to_receiver(params["send_to_receiver"], params["payment_method_token"], flight_id)

    case response do 
      {:ok, body} -> conn
        |> put_flash(:success, 
          "Successfully purchased #{flight.airline} Flight ##{flight.number}! Spreedly responded w/ #{body["transaction"]["response"]["message"]} ")
        |> put_session(:flight_details, params)
        |> redirect(to: flight_path(conn, :confirmation))
      {:error, body} -> conn
        |> put_flash(:error, "Failed to purchase flight. Response from Spreedly -> #{body["transaction"]["message"]}")
        |> render("show.html", id: params["id"], flight: flight)
    end
  end

  def show(conn, %{"id" => id}) do
    flight = find_flight(id)

    case flight do
      nil -> conn 
        |> put_status(:not_found) 
        |> render(SpreedlyAirlinesElixir.ErrorView, "404.html")
      _ -> render(conn, "show.html", [id: id, flight: flight])
    end
  end

  def confirmation(conn, _params) do
    details = get_session(conn, :flight_details)
    flight = find_flight(details["id"])
    user = for {key, val} <- details, into: %{}, do: {String.to_atom(key), val}

    render(conn, "confirmation.html", flight: flight, user: user)
  end 


  def make_purchase(flight, params) do
    build_transaction(flight, params) |> @spreedly.purchase()
  end

  def deliver_to_receiver("true", payment_method_token, flight_id) do
    build_delivery(payment_method_token, flight_id) |> @spreedly.deliver_to_receiver()
  end

  def deliver_to_receiver(_deliver, _payment_method_token, _flight_id), do: Logger.debug "Skipping delivery"
  
  defp build_transaction(flight, params) do 
    %Spreedly.Transaction { transaction: 
      %Spreedly.Payment{
        payment_method_token: params["payment_method_token"], 
        amount: trunc(flight.price * 100), 
        email: params["email"],
        retain_on_success: params["save_payment_info"],
        description: "#{flight.airline} Flight ##{flight.number}, #{flight.from} to #{flight.to}"
      }
    }
  end

  defp build_delivery(payment_method_token, id) do
    %{ delivery: %{
        payment_method_token: payment_method_token,
        url: "http://posttestserver.com/post.php",
        headers: "Content-Type: application/json",
        body: "{ \"flight_id\": \"#{id}\", \"card_number\": \"{{credit_card_number}}\" }"
      }
    }
  end 

  defp find_flight(id) do
    SpreedlyAirlinesElixir.FlightView.flights[id]
  end 
end

web/controllers/page_controller.ex
defmodule SpreedlyAirlinesElixir.PageController do
  use SpreedlyAirlinesElixir.Web, :controller

  require Logger


  def index(conn, _params) do
    render conn, "index.html"
  end

end

web/controllers/transaction_controller.ex
defmodule SpreedlyAirlinesElixir.TransactionController do
  use SpreedlyAirlinesElixir.Web, :controller

  require Logger

  @spreedly Application.get_env(:spreedly_airlines_elixir, :spreedly)

  def index(conn, _params) do
    response = @spreedly.list_transactions()

    case response do
      {:ok, body} -> conn
        |> render("index.html", transactions: body["transactions"])
      {:error, body} -> conn 
        |> put_flash(:error, "No transactions found!")
        |> render("index.html", transactions: [])
    end
  end

  def show(conn, %{"token" => token}) do
    response = @spreedly.show_transaction(token)

    case response do
      {:ok, body} -> conn
        |> render("show.html", transactions: body["transaction"], raw: Poison.encode!(body))
      {:error, body} -> conn 
        |> put_flash(:error, "Transaction not found, unable to find token #{token}!")
        |> render("show.html", raw: [])
    end
  end

end

web/views/error_view.ex
defmodule SpreedlyAirlinesElixir.ErrorView do
  use SpreedlyAirlinesElixir.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/flight_view.ex
defmodule SpreedlyAirlinesElixir.FlightView do
  use SpreedlyAirlinesElixir.Web, :view

  def flights do 
    %{
      "1" => %{:number => "14980", :airline => "Spreedly Airlines", :from => "AMA", :to => "RDU", :price => 545.36},
      "2" => %{:number => "4151", :airline => "Spreedly Airlines", :from => "DFW", :to => "SFO", :price => 192.12},
      "3" => %{:number => "19068", :airline => "Spreedly Airlines", :from => "LAX", :to => "DXB", :price => 886.95},
      "4" => %{:number => "69900", :airline => "Spreedly Airlines", :from => "DFW", :to => "HKG", :price => 743.51},
      "5" => %{:number => "8756", :airline => "Spreedly Airlines", :from => "AMA", :to => "CDG", :price => 1472.34}
    }
  end

end

web/views/layout_view.ex
defmodule SpreedlyAirlinesElixir.LayoutView do
  use SpreedlyAirlinesElixir.Web, :view

  def flash_messages(conn, key) do
    case get_flash(conn, key) do
      [_ | _] = messages -> messages
      nil -> []
      message -> [message]
    end
  end
end

web/views/page_view.ex
defmodule SpreedlyAirlinesElixir.PageView do
  use SpreedlyAirlinesElixir.Web, :view

end

web/views/transaction_view.ex
defmodule SpreedlyAirlinesElixir.TransactionView do
  use SpreedlyAirlinesElixir.Web, :view

  def render("scripts.show.html", _assigns) do
    ~s{<script>require("web/static/js/views/transaction/show").JSONFormat.run()</script>}
    |> raw
  end

end

web/templates/flight/confirmation.html.eex
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Flight Info</h3>
  </div>
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dt>Airline</dt>
      <dd id="airline"><%= @flight.airline %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt>Flight Number</dt>
      <dd id="flight_number">#<%= @flight.number %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt>Flight Info</dt>
      <dd id="flight_info"><%= @flight.from %> to <%= @flight.to %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt>Trip Total</dt>
      <dd id="total"><%= Number.Currency.number_to_currency(@flight.price) %></dd>
    </dl>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Passenger Info</h3>
  </div>
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dt>Full Name</dt>
      <dd id="full_name"><%= @user.full_name %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt>Email</dt>
      <dd id="email"><%= @user.email %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt>Payment Info Saved?</dt>
      <dd id="payment_info_saved"><%= @user.save_payment_info %></dd>
    </dl>
      <dl class="dl-horizontal">
      <dt>Delivered to Receiver?</dt>
      <dd id="payment_info_saved"><%= @user.send_to_receiver %></dd>
    </dl>
  </div>
</div>


<div>
  <%= link "View Flights", to: flight_path(@conn, :index) %>
</div>

web/templates/flight/index.html.eex
<div>
  <h2>Spreedly Airlines Flights</h2>

  <table class="table table-striped">
    <thead>
      <tr>  
        <th>Flight Number</th>
        <th>Airline</th>
        <th>From</th>
        <th>To</th>
        <th>Total Price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= for {id, f} <- flights() do %>
      <tr> 
        <th scope="row"><%= f.number %></th> 
        <td><%= f.airline %></td>
        <td><%= f.from %></td>
        <td><%= f.to %></td>
        <td><%= Number.Currency.number_to_currency(f.price) %></td>
        <td><%= link("Buy", to: flight_path(@conn, :show, id), class: "btn btn-primary btn-xs", role: "button")%></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

web/templates/flight/show.html.eex
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Flight Info</h3>
  </div>
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dt>Airline</dt>
      <dd id="airline"><%= @flight.airline %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt>Flight Number</dt>
      <dd id="flight_number">#<%= @flight.number %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt>Flight Info</dt>
      <dd id="flight_info"><%= @flight.from %> to <%= @flight.to %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt>Trip Total</dt>
      <dd id="total"><%= Number.Currency.number_to_currency(@flight.price) %></dd>
    </dl>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Passenger Info</h3>
  </div>
  <div class="panel-body">

    <%= form_for @conn, flight_path(@conn, :purchase), [class: "form-horizontal", id: :flight_form,  as: :flight_form], fn form -> %>
      <div class="form-group">
        <label for="inputFullName" class="col-sm-2 control-label">Full Name</label>
        <div class="col-sm-10">
          <%= email_input(form, :full_name, [class: "form-control", placeholder: "Full Name"]) %>
        </div>
      </div>
      <div class="form-group">
        <label for="inputEmail" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
          <%= email_input(form, :email, [class: "form-control", placeholder: "Email"]) %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div class="checkbox">
            <label>
              <%= checkbox(form, :save_payment_info) %> Save payment method?
            </label>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div class="checkbox">
            <label>
              <%= checkbox(form, :send_to_receiver) %> Send to receiver?
            </label>
          </div>
        </div>
      </div>
      <%= hidden_input(form, :id, value: @id) %>
      <%= hidden_input(form, :payment_method_token) %>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button id="checkout" type="button" class="btn btn-primary" onclick="handlePurchase();">Checkout</button>
        </div>
      </div>
    <% end %>
  </div>
</div>


<div>
  <%= link "View Flights", to: flight_path(@conn, :index) %>
</div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Spreedly Airlines Elixir</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><a href="<%= page_path(@conn, :index)%>">Home</a></li>
              <li><a href="<%= flight_path(@conn, :index)%>">Find Flights</a></li>
              <li><a href="<%= transaction_path(@conn, :index)%>">View Transactions</a></li>
            </ul>
            
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

      <p class="alert alert-success" role="alert"><%= get_flash(@conn, :success) %></p>
      <%= for message <- flash_messages(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <%= end %>
      <p class="alert alert-warning" role="alert"><%= get_flash(@conn, :warning) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="https://core.spreedly.com/iframe/express-2.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <%= render_existing @view_module, "scripts." <> @view_template, assigns %>
  </body>
</html>

web/templates/page/flights.html.eex
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div>
  <table class="table table-striped">
    <thead>
      <tr>  
        <th>Flight Number</th>
        <th>Airline</th>
        <th>From</th>
        <th>To</th>
        <th>Price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= for f <- @flights do %>
      <tr> 
        <th scope="row"><%= f.number %></th> 
        <td><%= f.airline %></td>
        <td><%= f.from %></td>
        <td><%= f.to %></td>
        <td><%= Number.Currency.number_to_currency(f.price) %></td>
        <td><%= link("Buy", to: "/", class: "btn btn-primary btn-xs", role: "button")%></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Spreedly Airlines!" %></h2>
  <p class="lead">A superior airline that uses Spreedly to communicate with your payment gateways and payments endpoints.</p>
  <p><a href="<%= flight_path(@conn, :index)%>" class="btn btn-primary btn-lg" role="button">Find Flights</a></p>
</div>

web/templates/transaction/index.html.eex
<div>
<h3>View Latest Transactions</h3>

  <table class="table table-striped">
    <thead>
      <tr>  
        <th>Transaction Type</th>
        <th>Created At</th>
        <th>State</th>
        <th>Amount</th>
        <th>Retain?</th>
        <th>Response</th>
        <th>Last 4</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= for t <- @transactions do %>
      <tr> 
        <td><%= t["transaction_type"] %></td>
        <td><%= t["created_at"] %></td>
        <td><%= t["state"] %></td>
        <td><%= t["amount"] %></td>
        <td><%= t["retain_on_success"] %></td>
        <td><%= t["response"]["message"] %></td>
        <td><%= t["payment_method"]["last_four_digits"] %></td>
        <td><%= link("Detail", to: transaction_path(@conn, :show, t["token"]), class: "btn btn-primary btn-xs", role: "button") %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

web/templates/transaction/show.html.eex
<h2>Transaction detail</h2>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Raw Json</h3>
  </div>
  <div class="panel-body">
    <pre id="raw">
        <%= @raw %>
    </pre>
  </div>
</div>
</ul>

<%= link "Back to transactions", to: transaction_path(@conn, :index) %>